### ISSUE TITLE
Person of the Year

### ISSUE THREAD

**Issue by rkaranam** [fcc-hyd/hackermonth#13]
**Person of the Year**
1. Lists all the important personalities in last one year.
2. Can add a person to the list if he/she is not there.
3. A person must be authenticated to vote.
4. Shows numbers of votes polled for a person at any time in the form of bar chart/pie chart/graph.
5. Cannot add a person after first elimination.
6. System automatically eliminates half of the persons after a period of time and the process repeats till only one person is left.
7. Only one person is elected as 'Person of the Year' at the end of the poll.

**Comment by duttakapil** [comment]
Hey @rkaranam, I like this idea. Have you formed a team around this? Or joined another team perhaps? If it's the later, let me know, so that I can close this issue. If you're looking for people to join your team, I'll be adding you to our WhatsApp group (if you've filled the form) and you can ask there if anyone would like to contribute. Keep me updated :)
